src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=ReclamationRepository::class)
 */
class Reclamation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez remplir ce champ !")
     * @Assert\Length(
     *     min = 3,
     *     max = 50,
     *     minMessage= "Le nom  est trop court",
     *     maxMessage="Le nom est trop long"
     * )
     */
    private $NomUser;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez remplir ce champ !")
     * @Assert\Length(
     *     min = 5,
     *     max=250,
     *     minMessage= "Le message  est trop court",
     *     maxMessage="Le message est trop long")
     */
    private $Message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\OneToMany(targetEntity=Reponses::class, mappedBy="reclamation", cascade={"remove"})
     */
    private $reponses;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="reclamations")
     */
    private $categorie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $rep;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez remplir ce champ !")
     * @Assert\Email(message = "Ce mail '{{ value }}' n'est pas valide.")
     */

    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $etat;





    public function __construct()
    {
        $this->reponses = new ArrayCollection();


    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomUser(): ?string
    {
        return $this->NomUser;
    }

    public function setNomUser(string $NomUser): self
    {
        $this->NomUser = $NomUser;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    /**
     * @return Collection|Reponses[]
     */
    public function getReponses(): Collection
    {
        return $this->reponses;
    }

    public function addReponse(Reponses $reponse): self
    {
        if (!$this->reponses->contains($reponse)) {
            $this->reponses[] = $reponse;
            $reponse->setReclamation($this);
        }

        return $this;
    }

    public function removeReponse(Reponses $reponse): self
    {
        if ($this->reponses->removeElement($reponse)) {
            // set the owning side to null (unless already changed)
            if ($reponse->getReclamation() === $this) {
                $reponse->setReclamation(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getRep(): ?string
    {
        return $this->rep;
    }

    public function setRep(string $rep): self
    {
        $this->rep = $rep;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(?string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }



   }

pi/avengers/src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')

            ->add('submit',SubmitType::class)
            ->add('cancel',ResetType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('catrec')
            ->add('descrip')
            ->add('level', ChoiceType::class, [
                'choices'  => [
                    'high' => 'high',
                    'medium' => 'medium',
                    'low' => 'low',
                ],
            ])
            ->add('submit',SubmitType::class)
            ->add('cancel',ResetType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

pi/avengers/src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizableInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class CategorieController extends AbstractController
{
    /**
     * @Route("/categorie", name="categorie")
     */
    public function index(): Response
    {
        return $this->render('categorie/index.html.twig', [
            'controller_name' => 'CategorieController',
        ]);
    }

    /**
     * @param CategorieRepository $repository
     * @return Response
     * @route ("/AfficheCat", name="AfficheCat")
     */
    function Affiche(CategorieRepository $repository){
        //$repo= $this->getDoctrine()->getRepository(Classroom::class);
        $categorie= $repository->findAll();
        return $this->render('/categorie/AfficheCat.html.twig',['categorie'=>$categorie]);
    }

    /**
     * @param $id
     * @param CategorieRepository $rep
     * @route ("/DeleteCat/{id}", name="dcat")
     */
    function Delete($id,CategorieRepository $rep){
        $categorie=$rep->find($id);
        $em=$this->getDoctrine()->getManager();
        $em->remove($categorie);
        $em->flush();
        return $this->redirectToRoute('AfficheCat');
    }

    /**
     * @param Request $request
     * @return Response
     * @route ("/AjoutCat", name="Acat")
     */

    function Ajout(Request $request){
        $categorie=new Categorie();
        $form=$this->createForm(CategorieType::class,$categorie);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($categorie);
            $em->flush();
            return $this->redirectToRoute('AfficheCat');
        }
        return $this->render('categorie/AjoutCat.html.twig',['fcat'=>$form->createView()]);
    }

    /**
     * @Route("/UpdateCat/{id}",name="Ucat")
     */
    function Update(CategorieRepository $repository,$id,Request $request)
    {
        $categorie = $repository->find($id);
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("AfficheCat");
        }
        return $this->render('categorie/UpdateCat.html.twig',
            [
                'fcat' => $form->createView(),
                "form_title" => "Modifier une catégorie"
            ]);
    }

    /**
     *
     * @route ("/addcatJSON/new",name="addcat")
     */
    public function addpcat(Request $request,NormalizerInterface $Normalizer)
    {
        $em=$this->getDoctrine()->getManager();
        $categorie=new Categorie();
        $categorie->setNom($request->get('nom'));
        $em->persist($categorie);
        $em->flush();
        $jsonContent=$Normalizer->normalize($categorie,'json',['groups'=>'post:read']);
        return new Response(json_encode($jsonContent));;
    }

    /**
     * @Route("/Categorie/{id}",name="allcat")
     */
    public function catid(Request $request, $id, NormalizerInterface $Normalizer)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository(Categorie::class)->find($id);
        $jsonContent = $Normalizer->normalize($user, 'json', ['groups'=>'post:read']);

        return new Response(json_encode($jsonContent));
    }

    /**
     * @Route ("/updateCategorieJSON/{id}", name="updateCategorieJSON")
     */
    public function updateCategorieJSON(Request $request,NormalizerInterface $normalizer,$id)
    {
        $em=$this->getDoctrine()->getManager();
        $categorie=$em->getRepository(Categorie::class)->find($id);
        $categorie->setNom($request->get('nom'));
        $em->flush();
        $jsonContent=$normalizer->normalize($categorie,'json', ['groups'=>'post:read']);
        return new Response("Information updated successfully".json_encode($jsonContent));;
    }

}

smfCRUD/src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Form\ProduitType;
use App\Repository\CategorieRepository;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Ob\HighchartsBundle\Highcharts\Highchart;

use Symfony\Component\Routing\Annotation\Route;

class CategorieController extends Controller
{
    /**
     * @Route("/categorie", name="categorie")
     */
    public function index(): Response
    {
        return $this->render('categorie/index.html.twig', [
            'controller_name' => 'CategorieController',
        ]);
    }

    /**
     * @Route("/CategorieM",name="allcat")
     */
    public function catid(Request $request, NormalizerInterface $Normalizer)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository(Categorie::class)->findAll();
        $jsonContent = $Normalizer->normalize($user, 'json', ['groups'=>'post:read']);

        return new Response(json_encode($jsonContent));
    }





/**
*
* @route ("/addcatJSON/new",name="addcat")
*/
    public function addpcat(Request $request,NormalizerInterface $Normalizer)
    {
        $em=$this->getDoctrine()->getManager();
        $categorie=new Categorie();
        $categorie->setNomCateg($request->get('nom_categ'));
        $categorie->setMailFournisseur($request->get('mail_fournisseur'));
        $categorie->setNomFournisseur($request->get('nom_fournisseur'));


        $em->persist($categorie);
        $em->flush();
        $jsonContent=$Normalizer->normalize($categorie,'json',['groups'=>'post:read']);
        return new Response(json_encode($jsonContent));;




    }


    /**
     * @Route ("/updatecatJSON/{id}", name="updatecatJSON")
     */
    public function updateCommentaireJSON(Request $request,NormalizerInterface $normalizer,$id)
    {
        $em=$this->getDoctrine()->getManager();
        $categorie=$em->getRepository(Commentaire::class)->find($id);
        $categorie->setNomCateg($request->get('nom_categ'));
        $categorie->setMailFournisseur($request->get('mail_fournisseur'));
        $categorie->setNomFournisseur($request->get('nom_fournisseur'));

        $em->flush();
        $jsonContent=$normalizer->normalize($categorie,'json', ['groups'=>'post:read']);
        return new Response("Information updated successfully".json_encode($jsonContent));;
    }



    /**
     * @param CategorieRepository $repository
     * @Route ("/Affichercat", name="affichcat")
     */
    public function Affiche(CategorieRepository  $repository,Request $request)

    {



        $ob = new Highchart();
        $ob->chart->renderTo('piechart');
        $ob->title->text('Browser market shares at a specific website in 2010');
        $ob->plotOptions->pie(array(
            'allowPointSelect' => true,
            'cursor' => 'pointer',
            'dataLabels' => array('enabled' => false),
            'showInLegend' => true
        ));
        $categories = $repository->findAll();
$data2=[];
        $categNom=[];
        $categCount=[];
        $somme=0;
        $compt[]=0;

        foreach($categories as $categorie){
            $categNom[] = $categorie->getNomCateg();
            $categCount[] = count($categorie->getProduits());

        }



        $i=0;


        foreach($categNom as $p)
        {

           /* $data2 = array(

                array( $categNom[0] , $categCount[0]),
                array( $categNom[1] , $categCount[1]),
                array( $categNom[2] , $categCount[2]),
                array( $categNom[3] , $categCount[3]),



                array( $categNom[$i] , $categCount[$i]),
            )
            ;*/


            array_push($data2,[$categNom[$i],$categCount[$i]]);
            $i++;




        }






        $ob->series(array(array('type' => 'pie','name' => 'Nombre de produits', 'data' => $data2)));


        $categorie=$repository->affich_produit_nbr();
        $allcategories = $this->get('knp_paginator')->paginate(
        // Doctrine Query, not results
            $categorie,
            // Define the page parameter
            $request->query->getInt('page', 1),
            3
        );
        return $this->render('categorie/affichcat.html.twig',['categorie'=>$allcategories, 'chart' => $ob]);

    }
    /**
     * @param ProduitRepository $repository
     * @Route ("/side", name="side")
     */
    public function Affichefronhome(ProduitRepository  $repository)
    {




        $produit=$repository->findAll();
        return $this->render('side.html.twig',['produit'=>$produit

]);

    }
    /**
     * @param $id
     * @param CategorieRepository $rep
     * @route ("/Deletecat/{id}", name="dcat")
     */
    function Delete($id,CategorieRepository $rep){
        $categorie=$rep->find($id);
        $em=$this->getDoctrine()->getManager();
        $em->remove($categorie);
        $em->flush();
        return $this->redirectToRoute('affichcat');
    }

    /**
     * @param Request $request
     * @return Response
     * @route ("/Ajoutcat", name="Acat")
     */

    function Ajout(Request $request)
    {





        $categorie=new Categorie();
        $form=$this->createForm(CategorieType::class,$categorie);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($categorie);
            $em->flush();
            return $this->redirectToRoute('affichcat');
        }
        return $this->render('categorie/ajoutcat.html.twig',[
            'f'=>$form->createView(),

        ]);
    }

    /**
     * @Route("categorie/Update/{id}",name="Upc")
     */
    function Update( CategorieRepository $repository,$id,Request $request)
    {
        $categorie = $repository->find($id);
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("affichcat");
        }
        return $this->render('categorie/updatecat.html.twig',
            [
                'f' => $form->createView(),
                "form_title" => "Modifier un type"
            ]);
    }


}

templates/categorie/Affichec.html.twig
{% extends 'crud.html.twig' %}
{% block body %}




    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Gestion des catégories</h4>

                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th> ID </th>
                            <th> Catégorie de la réclamation </th>
                            <th> Description de la catégorie  </th>
                            <th> Date </th>

                            <th> level </th>


                            <th>Delete</th>
                            <th>Update</th>

                        </tr>
                        </thead>
                        <tbody>

                        <tr {% for c in cat %}>

                            <td> {{ c.id }}</td>

                            <td> {{ c.catrec }}</td>
                            <td
                                    style="word-wrap: break-word;
                                min-width: 160px;
                                max-width: 160px;
                                white-space: normal;"
                            > {{ c.descrip }}</td>
                            <td> {{ c.date|date('d-m-Y H:i:s') }}</td>

                            <td> {{ c.level }}</td>




                            <td>  <a  href=" {{ path('dc',{'id':c.id}) }} "  > Delete
                                    <img src="back/images/faces/bin.jpg" alt="image"/>



                                </a>


                            </td>

                            <td><a href="{{ path('Uc',{'id':c.id}) }}" > Update</a> </td>




                        </tr {% endfor %}>
                        {{ knp_pagination_render(cat) }}


                        </tbody>


                    </table>
                    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"
                            type="text/javascript"></script>
                    <script src="//code.highcharts.com/4.0.1/highcharts.js"></script>
                    <script src="//code.highcharts.com/4.0.1/modules/exporting.js"></script>
                    <script type="text/javascript">
                        {{ chart(chart) }}
                    </script>
                    <div id="piechart" style="min-width: 400px; height: 400px; margin: 0 auto"></div>{# empty
Twig template #}

                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/categorie/Ajoutc.html.twig
{% extends 'crud.html.twig' %}

{% block body %}
    <div class="card-body">
        <h4 class="card-title">Ajouter une catégorie</h4>
        <p class="card-description">
        </p>

        {{ form_start(f) }}
        <form class="forms-sample">

            <div class="form-group">
                {{ form_label(f.catrec, 'Categorie', ) }}
                {{ form_widget(f.catrec, {'attr': {'class': 'form-control','placeholder': 'Categorie'}}) }}
                {{ form_errors(f.catrec) }}

            </div>

            <div class="form-group">
                {{ form_label(f.descrip, 'Description', ) }}
                {{ form_widget(f.descrip, {'attr': {'class': 'form-control','placeholder': 'Description'}}) }}
                {{ form_errors(f.descrip) }}

            </div>

            <div class="form-group">
                {{ form_label(f.level, 'level', ) }}
                {{ form_widget(f.level, {'attr': {'class': 'form-control','placeholder': 'level'}}) }}
                {{ form_errors(f.level) }}

            </div>



            <div class="input-group col-md-6">
                {{ form_widget(f.submit, {'attr': {'class': 'form-control btn btn-primary mr-2' }}) }}
                {{ form_widget(f.cancel, {'attr': {'class': 'btn btn-danger' }}) }}
            </div>
            {{ form_end(f) }}
        </form>

    </div>





{% endblock %}

templates/categorie/Updatec.html.twig
{% extends 'crud.html.twig' %}


{% block stylesheets %}

    <link href="{{ asset('back/vendors/feather/feather.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ asset('back/vendors/ti-icons/css/themify-icons.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ asset('back/vendors/css/vendor.bundle.base.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ asset('back/vendors/datatables.net-bs4/dataTables.bootstrap4.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ asset('back/vendors/ti-icons/css/themify-icons.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ asset('back/js/select.dataTables.min.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ asset('back/css/vertical-layout-light/style.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ asset('back/images/favicon.png') }}" type="text/css" rel="shortcut icon" />





{% endblock %}


{% block body %}
    <div class="card-body">
        <h4 class="card-title">Modifier une catégorie</h4>
        <p class="card-description">
        </p>

        {{ form_start(f) }}
        <form class="forms-sample">

            <div class="form-group">
                {{ form_label(f.catrec, 'Categorie', ) }}
                {{ form_widget(f.catrec, {'attr': {'class': 'form-control','placeholder': 'Categorie'}}) }}
                {{ form_errors(f.catrec) }}
            </div>

            <div class="form-group">
                {{ form_label(f.descrip, 'Description', ) }}
                {{ form_widget(f.descrip, {'attr': {'class': 'form-control','placeholder': 'Description'}}) }}
                {{ form_errors(f.descrip) }}
            </div>




            <div class="input-group col-md-6">
                {{ form_widget(f.submit, {'attr': {'class': 'form-control btn btn-primary mr-2' }}) }}
                {{ form_widget(f.cancel, {'attr': {'class': 'form-control btn btn-light mr-2' }}) }}
            </div>
            {{ form_end(f) }}
        </form>

    </div>
{% endblock body %}