Esports-Application/src/Entity/Adresse.php
<?php

namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;

use App\Repository\AdresseRepository;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=AdresseRepository::class)
 */
class Adresse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank(message="Name is required")
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank(message="Last Name is required")
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank(message="Adress is required")
     */
    private $Adress;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank(message="City is required")
     */
    private $City;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank(message="Email is required")
     * @Assert\Email(message = "The email '{{ value }}' is not a valid email.")
     */
    private $Email;

    /**
     * @ORM\Column(type="integer")
     *  @Assert\Length(
     *     min = 8,
     *     max = 8,
     *     minMessage= "Le N°tel  est trop court",
     *     maxMessage="Le N°tel est trop long")
     * @Assert\NotBlank (message="Phone  is required")
     */
    private $Tel;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="adresse")
     */
    private $Commande;
    /**
     * @ORM\Column (type="string" , length=8)
     */
    private $codepromo;

    /**
     * @return mixed
     */
    public function getCodePromo()
    {
        return $this->codepromo;
    }

    /**
     * @param mixed $codepromo
     */
    public function setCodePromo($codepromo): void
    {
        $this->codepromo = $codepromo;
    }


    public function __construct()
    {
        $this->Commande = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->Adress;
    }

    public function setAdress(string $Adress): self
    {
        $this->Adress = $Adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getTel(): ?int
    {
        return $this->Tel;
    }

    public function setTel(int $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommande(): Collection
    {
        return $this->Commande;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->Commande->contains($commande)) {
            $this->Commande[] = $commande;
            $commande->setAdresse($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->Commande->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getAdresse() === $this) {
                $commande->setAdresse(null);
            }
        }

        return $this;
    }
}

Esports-Application/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Classroom;
use App\Entity\User;
use App\Form\ClassroomType;
use App\Form\MdpType;
use App\Form\PasswordType;
use App\Form\UserType;
use App\Repository\ClassroomRepository;
use App\Repository\EquipeRepository;
use App\Repository\UserRepository;
use mysql_xdevapi\Session;
use phpDocumentor\Reflection\Types\Null_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Serializer\Normalizer\NormalizableInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Twilio\Rest\Client;


class UserController extends AbstractController
{
    /**
     * @Route("/user", name="user")
     */
    public function index(): Response
    {
        return $this->render('base.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }


    /**
     * @param UserRepository $repository
     * @return Response
     * @Route("f/afficheuser",name="afficheruser")
     */

    public function AfficherUser(UserRepository $repository, Request $request, UserPasswordEncoderInterface $passwordEncoder, \Swift_Mailer $mailer)
    {
        $em = $this->getDoctrine()->getManager();
        $session = $request->getSession();

        $users = $repository->findAll();
        $user1 = $this->get('security.token_storage')->getToken()->getUser();

        return $this->render('front/user/afficheuser.html.twig', [
            'u' => $users]);

    }

    /**
     * @param UserRepository $repository
     * @return Response
     * @Route("/back/afficheuserback",name="afficheruserbackee")
     */

    public function AfficherUserBack(UserRepository $repository, Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $users = $repository->findAll();
        return $this->render('/back/userback/afficheuserback.html.twig', [
            'u' => $users]);

    }


    /**
     * @Route("/supprimeruser/{id}",name="d")
     * @param $id
     * @param UserRepository $repository
     * @return RedirectResponse
     */
    function Delete($id, UserRepository $repository)
    {
        $user = $repository->find($id);
        $em = $this->getDoctrine()->getManager();
        $em->remove($user);
        $em->flush();
        return $this->redirectToRoute('front/user/afficheruser');

    }

    /**
     * @Route("/back/supprimeruserback/{id}",name="dback")
     * @param $id
     * @param UserRepository $repository
     * @return RedirectResponse
     */
    function Deleteback($id, UserRepository $repository)
    {
        $user = $repository->find($id);
        $em = $this->getDoctrine()->getManager();
        $em->remove($user);
        $em->flush();
        return $this->redirectToRoute('afficheruserbackee');

    }


    /**
     * @param Request $request
     * @return Response
     * @Route("/AddUser",name="a")
     */
    function Add(Request $request, UserPasswordEncoderInterface $passwordEncoder, \Swift_Mailer $mailer,EquipeRepository $repequipe)
    {
        $user = new User();
        $session = $request->getSession();


        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
          /*  $session->set('ok', $passwordEncoder->encodePassword(
                $user,
                $form->get('password')->getData()
            ));

            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );*/
            $user->setBlock(false);
            $equipe=$repequipe->find(7);
            $user->setEquipe($equipe);
            $em = $this->getDoctrine()->getManager();

            $message = (new \Swift_Message('Mail Admin'))
                ->setFrom('mohamedkhalil.trabelsi@esprit.tn')
                ->setTo($user->getEmail())
                ->setBody(
                    "Bienvenue Cher " . $user->getUsername() . " , L'equipe e-tsports vous souhaite une experience"
                );

            $mailer->send($message);
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('app_login');
        }
        return $this->render('front/user/useradd.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @param Request $request
     * @return Response
     * @Route("/back/AddUserback",name="aback")
     */
    function AddBack(Request $request, UserPasswordEncoderInterface $userPasswordEncoder,EquipeRepository $repequipe)
    {
        $user = new User();
        $session = $request->getSession();
        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);
        $user->setBlock(false);
        $equipe=$repequipe->find(7);
        $user->setEquipe($equipe);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('afficheruserbackee');
        }
      ;
        return $this->render('back/userback/useraddback.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/updatefront/{id}",name="m")
     */
    function modifier(UserRepository $repository, $id, Request $request, \Swift_Mailer $mailer,UserPasswordEncoderInterface $userPasswordEncoder)
    {
        $user = $repository->find($id);
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        $p=$form->get('password')->getData();
        //$p=$userPasswordEncoder->encodePassword($user,$p);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("afficheruser");
        }
        return $this->render("front/user/updateuser.html.twig", ['f' => $form->createView()]);

    }

    /**
     * @Route("/updatemdp/{id}",name="modifiermdp")
     */
    function modifiermdp(UserRepository $repository, $id, Request $request, \Swift_Mailer $mailer, UserPasswordEncoderInterface $passwordEncoder)
    {
        $user = $repository->find($id);

        $form = $this->createForm(PasswordType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            echo "ahla ena user";
            $data = $form->get('password')->getData();
           // $user->setPassword($passwordEncoder->encodePassword($user, $data));
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("app_login");
        }
        return $this->render("front/user/updatemdp..html.twig", ['f' => $form->createView()]);

    }

    /**
     * @Route("/mdp",name="mdp")
     */
    function mdp(UserRepository $repository, Request $request, \Swift_Mailer $mailer)
    {
        $form = $this->createForm(MdpType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->get('email')->getData();
            $user = $repository->findByEmail($data);

            if ($user instanceof User) {
                $message = (new \Swift_Message('Mail Admin'))
                    ->setFrom('mohamedkhalil.trabelsi@esprit.tn')
                    ->setTo($user->getEmail())
                    ->setBody(" Salut cher Gamer, Accedez à ce lien pour changer votre mot de passe 
                     http://localhost:8000/updatemdp/" . $user->getId() . "    
                       Soyez mefiant"

                    );

                $mailer->send($message);

                return $this->redirectToRoute("mdp");
            } else return $this->redirectToRoute("app_login");


        }
        return $this->render("front/user/mdp.html.twig", ['f' => $form->createView()]);

    }


    /**
     * @Route("/back/updateback/{id}",name="mback")
     */
    function modifierback(UserRepository $repository, $id, Request $request)
    {
        $user = $repository->find($id);
        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("afficheruserbackee");
        }
        return $this->render("back/userback/updateuserback.html.twig", ['f' => $form->createView()]);

    }

    /**
     * @param UserRepository $repository
     * @param $id
     * @return Response
     * @Route("/noteam/{id}",name="noteam")
     */
    public function displayuser(UserRepository $repository, Request $request, $id)
    {
        $session = $request->getSession();
        $session->set('idaz', $id);
        $users = $repository->Usernoteam();
        return $this->render('front/user/noteam.html.twig', [
            'u' => $users]);

    }

    /**
     * @Route("/searchuserajax ", name="userOffre")
     */
    public function searchOffreajax(Request $request)
    {
        $repository = $this->getDoctrine()->getRepository(User::class);
        $requestString = $request->get('searchValue');
        $user = $repository->findUSERbyname($requestString);
        return $this->render('front/user/userajax.html.twig', [
            "u" => $user
        ]);
    }


    /**
     * @param UserRepository $repository
     * @param $id
     * @return Response
     * @Route("back/noteamback/{id}",name="noteamback")
     */

Esports-Application/templates/front/user/afficheuser.html.twig
{% extends 'front.html.twig' %}


{% block body %}
<body>

<style>
    tr{
        background-color: #171E22;
    }
</style>

<div class="col-lg-12 stretch-card">
    <div class="card">
        <div class="card-body" style="background-color: #171E22">
            <h4 class="card-title">Les membres E-Tsports</h4>
            <p class="card-description">
                </code>
            </p>
            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <thead>
                    <tr>

                        <th>
                            First name
                        </th>
                        <th>
                          Last name
                        </th>
                        <th>
                          Email
                        </th>
                        <th>
                            Date De Naissance
                        </th>
                        <th>
                            Sexe
                        </th>
                        <th>
                            Equipe
                        </th>

                        <th>
                            Delete
                        </th>
                        <th>
                           Modify
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for u in u %}
                        <tr >


                            <td>
                                {{ u.nom }}
                            </td>

                            <td>
                                {{ u.prenom}}
                            </td>

                            <td>
                                {{ u.email}}
                            </td>

                            <td>
                                {{ u.dateN |date('d-m-Y') }}
                            </td>

                            <td>
                                {{u.sexe}}
                            </td>

                            <td>
                                {% if u.equipe is not null %}

                                    {{u.equipe.NomEquipe}}

                                {% endif %}
                            </td>


                            <td>
                                {% if is_granted("ROLE_CLIENT") and app.user.id==u.id %}
                                <a href="{{ path('d',{'id':u.id}) }}"> Delete</a>
                                {% endif %}
                            </td>

                            <td>

                                {% if is_granted("ROLE_CLIENT") and app.user.id==u.id %}
                                <a href="{{ path('m',{'id':u.id}) }}"> Modify</a>
                                {% endif %}
                            </td>

                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
</div>









</table>

 <a href="{{ path('ajouterequipe') }}" class="btn-danger btn-lg" style="margin-left: 45%" > ajouter equipe</a>

</body>
{% endblock %}

Esports-Application/templates/front/user/block.html.twig
{% extends 'front.html.twig' %}

{% block block %}

 {% endblock %}
{% block body %}

<h1>VOUS ETES BLOQUES</h1>
{% endblock %}

Esports-Application/templates/front/user/mdp.html.twig
{% extends 'front.html.twig' %}
{% block body %}
    <h4>Saisir votre email afin de recuperer votre mot de passe :)</h4>
    {{ form_start(f) }}
    <div class="form-group">
        {{ form_label(f.email, 'Email', ) }}
        {{ form_widget(f.email, {'attr': {'class': 'form-control','placeholder': 'Email'}}) }}
    </div>
    <div class="input-group col-md-6">
        {{ form_widget(f.submit, {'attr': {'class': 'form-control btn btn-primary mr-2' }}) }}
        {{ form_widget(f.cancel, {'attr': {'class': 'form-control btn btn-light mr-2' }}) }}
    </div>
    {{ form_end(f) }}
{% endblock %}

Esports-Application/templates/front/user/noteam.html.twig
{% extends 'front.html.twig' %}

{% block body %}
    <body>

    <style>
        tr{
            background-color: #171E22;
        }
    </style>

    <div class="col-lg-12 stretch-card">
        <div class="card">
            <div class="card-body" style="background-color: #171E22">
                <h4 class="card-title">Les membres E-Tsports Qui N'ont Pas D'equipes</h4>
                <p class="card-description">
                    </code>
                </p>
                <div class="table-responsive pt-3">
                    <form class="w-search">
                        <div class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" id="search" class="form-control" placeholder="Search">
                            </div>
                            <!-- /input-group -->
                        </div>
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="#"><span class="fa arrow"></span></a>
                                <ul style="background-color: #0b0b0b" class="nav " id="entitiesNav">
                                </ul>
                            </li>
                        </ul>
                    </form>
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nom</th>
                            <th>Prenom</th>
                            <th>Email</th>
                            <th>DateN</th>
                            <th>Sexe</th>
                            <th>Equipe</th>

                            <th>ajouter à l'equipe</th>
                        </tr>
                        </thead>
                        <tbody id="all">
                              {% include 'front/user/userajax.html.twig' %}
                        </tbody>
                        <tbody id="search">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </table>
    <a href="{{ path('ajouterequipe') }}"class="btn-danger btn-lg" style="margin-left: 30%"> ajouter equipe</a>
    </body>
    <script src="{{ asset('assets/js/jquery.js') }}"></script>
    <script
            src="{{ asset('https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js')}}">
    </script>
    <script>
        $( document ).ready(function() {
            var currentRequest = null;
            $("#search").keyup(function(e){
                /* La variable value va prendre la valeur insérer dans le champ de texte
                afin d’effectuer la recherche */
                var value = $(this).val();
                if(currentRequest != null) {
                    currentRequest.abort();
                }
                /* Ajax est lancé lors du remplissage du champ texte dont l’id est
                « search » pour faire la recherche */
                currentRequest = $.ajax({
                    url : "{{ path('userOffre') }}",
                    type : 'GET',
                    data: {
                        'searchValue' : value
                    },
                    success : function(retour)
                    {
                        $('#all').html(retour);
                    },
                });
                return false;
            });
        });
    </script>

{% endblock %}

Esports-Application/templates/front/user/updatemdp..html.twig
{% extends 'front.html.twig' %}
{% block body %}
    {{ form_start(f) }}
    <div class="form-group">
        {{ form_label(f.password, 'password', ) }}
        {{ form_widget(f.password, {'attr': {'class': 'form-control','placeholder': 'password'}}) }}
    </div>
    <div class="input-group col-md-6">
        {{ form_widget(f.submit, {'attr': {'class': 'form-control btn btn-primary mr-2' }}) }}
        {{ form_widget(f.cancel, {'attr': {'class': 'form-control btn btn-light mr-2' }}) }}
    </div>
    {{ form_end(f) }}
{% endblock %}

Esports-Application/templates/front/user/updateuser.html.twig
{% extends 'front.html.twig' %}
{% block body %}
    <div class="card-body">
        <h4 class="card-title"><i class="fa-solid fa-circle-plus"></i>  Modifier</h4>
        <a class="btn btn-outline-dark " href="{{ path('afficheruser') }}"><i class="fa-solid fa-gamepad"></i> afficher les joueurs  </a>
        <p class="card-description">
        </p>

        {{ form_start(f) }}
        <form class="forms-sample">

            <div class="form-group">
                {{ form_label(f.nom, 'Nom ', ) }}
                {{ form_widget(f.nom, {'attr': {'class': 'form-control','placeholder': 'Nom du jeu'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(f.prenom, 'Prenom', ) }}
                {{ form_widget(f.prenom, {'attr': {'class': 'form-control','placeholder': 'Nom du jeu'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(f.email, 'Email', ) }}
                {{ form_widget(f.email, {'attr': {'class': 'form-control','placeholder': 'Type du jeu'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(f.dateN, 'Date de naissance', ) }}
                {{ form_widget(f.dateN, {'attr': {'class': 'form-control','placeholder': 'DD/MM/YYYY'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(f.tel, 'telephone', ) }}
                {{ form_widget(f.tel, {'attr': {'class': 'form-control','placeholder': 'telephone'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(f.sexe, 'sexe', ) }}
                {{ form_widget(f.sexe, {'attr': {'class': 'form-control','placeholder': 'sexe'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(f.password, 'password', ) }}
                {{ form_widget(f.password, {'attr': {'class': 'form-control','placeholder': 'password'}}) }}
            </div>
            <div class="form-check form-check-flat form-check-primary">
                <label class="form-check-label">
                    <input type="checkbox" class="form-check-input">
                    Remember me
                </label>
            </div>
            <div class="input-group col-md-6">
                {{ form_widget(f.submit, {'attr': {'class': 'form-control btn btn-primary mr-2' }}) }}
                {{ form_widget(f.cancel, {'attr': {'class': 'form-control btn btn-light mr-2' }}) }}
            </div>

            {{ form_end(f) }}
        </form>
        <a href="{{ path('suppequipe') }}">Supprimer ce joueur de l'equipe </a>

    </div>
{% endblock %}

Esports-Application/templates/front/user/useradd.html.twig
{% extends 'front.html.twig' %}
{% block titre1 %} Insciption Front {% endblock %}
{% block titre2 %} Insciption {% endblock %}
{% block top_bg %} "{{ asset('front/assets/images/gallery-3-thumb.jpg') }}" {% endblock %}
{% block bottom_bg %} "{{ asset('front/assets/images/bg-bottom.png') }}" {% endblock %}
{% block body %}



    <div class="card-body">
        <h4 class="card-title"><i class="fa-solid fa-circle-plus"></i>  ajouter des membres</h4>
        <a class="btn btn-outline-dark " href="
                                    {% if is_granted("ROLE_CLIENT") %}
                                    {{ path('afficheruser') }}"
        {% else %}
            "data-toggle="modal" data-target="#modalLogin"
        {% endif %}
        <i class="fa-solid fa-gamepad"></i> afficher les joueurs  </a>
        <p class="card-description">
        </p>
        <a </a>
        {{ form_start(form) }}
        <form class="forms-sample">

            <div class="form-group">
                {{ form_label(form.nom, 'Nom ', ) }}
                {{ form_widget(form.nom, {'attr': {'class': 'form-control','placeholder': 'Nom'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.prenom, 'Prenom', ) }}
                {{ form_widget(form.prenom, {'attr': {'class': 'form-control','placeholder': 'Prenom'}}) }}
                {{  form_errors(form.prenom)}}
            </div>
            <div class="form-group">
                {{ form_label(form.email, 'Email', ) }}
                {{ form_widget(form.email, {'attr': {'class': 'form-control','placeholder': 'Email'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.username, 'username', ) }}
                {{ form_widget(form.username, {'attr': {'class': 'form-control','placeholder': 'Username'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.dateN, 'Date de naissance', ) }}
                {{ form_widget(form.dateN, {'attr': {'class': 'form-control','placeholder': 'DD/MM/YYYY'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.tel, 'telephone', ) }}
                {{ form_widget(form.tel, {'attr': {'class': 'form-control','placeholder': 'telephone'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.sexe, 'sexe', ) }}
                {{ form_widget(form.sexe, {'attr': {'class': 'form-control','placeholder': 'sexe'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.password, 'password', ) }}
                {{ form_widget(form.password, {'attr': {'class': 'form-control','placeholder': 'password'}}) }}
                {{ form_errors(form.password)}}
            </div>
            <div class="form-group">

                {{ form_widget(form.captchaCode, {'attr': {'class': 'form-control','placeholder': 'Captcha'}}) }}
            </div>

            <div class="input-group col-md-6">
                {{ form_widget(form.submit, {'attr': {'class': 'form-control btn btn-primary mr-2' }}) }}
                {{ form_widget(form.cancel, {'attr': {'class': 'form-control btn btn-light mr-2' }}) }}
            </div>

            {{ form_end(form) }}
        </form>

    </div>
{% endblock %}